---
title: Nearshore and offshore co-occurrence of marine heatwaves and cold-spells
date: '2017-01-10'
author:
  - RW Schlegel
  - ECJ Oliver
  - T Wernberg
  - AJ Smit
subtitle: In *Progress in Oceanography*.
type: Journal article
categories:
  - R
  - coastal
  - marine heatwaves
  - marine cold-spells
---

A changing global climate places shallow water ecosystems at more risk than those in the open ocean as their temperatures may change more rapidly and dramatically. To this end, it is necessary to identify the occurrence of extreme ocean temperature events – marine heatwaves (MHWs) and marine cold-spells (MCSs) – in the nearshore (<400 m from the coastline) environment as they can have lasting ecological effects. The occurrence of MHWs have been investigated regionally, but no investigations of MCSs have yet to be carried out. The occurrence of MHWs have been investigated regionally, but no investigations of MCSs have yet to be carried out. A recently developed framework that defines these events in a novel way was applied to ocean temperature time series from (i) a nearshore in situ dataset and (ii) 1/4° NOAA Optimally Interpolated sea surface temperatures. Regional drivers due to nearshore influences (local-scale) and the forcing of two offshore ocean currents (broad-scale) on MHWs and MCSs were taken into account when the events detected in these two datasets were used to infer the links between offshore and nearshore temperatures in time and space. We show that MHWs and MCSs occur at least once a year on average but that proportions of co-occurrence of events between the broad- and local scales are low (0.20–0.50), with MHWs having greater proportions of co-occurrence than MCSs. The low rates of co-occurrence between the nearshore and offshore datasets show that drivers other than mesoscale ocean temperatures play a role in the occurrence of at least half of nearshore events. Significant differences in the duration and intensity of events between different coastal sections may be attributed to the effects of the interaction of oceanographic processes offshore, as well as with local features of the coast. The decadal trends in the occurrence of MHWs and MCSs in the offshore dataset show that generally MHWs are increasing there while MCSs are decreasing. This study represents an important first step in the analysis of the dynamics of events in nearshore environments, and their relationship with broad-scale influences.

**Links:** [PDF](https://doi.org/10.1016/j.pocean.2017.01.004) &middot; [Code](https://github.com/robwschlegel/MHW)
