---
title: Detecting Marine Heatwaves With Sub-Optimal Data
date: '2019-12-15'
author:
  - RW Schlegel
  - ECJ Oliver
  - AJ Hobday
  - AJ Smit
subtitle: In *Frontiers in Marine Science*.
type: Journal article
categories:
  - R
  - marine heatwaves
---

Marine heatwaves (MHWs), or prolonged periods of anomalously warm sea water temperature, have been increasing in duration and intensity globally for decades. However, there are many coastal, oceanic, polar, and sub-surface regions where our ability to detect MHWs is uncertain due to limited high quality data. Here, we investigate the effect that short time series length, missing data, or linear long-term temperature trends may have on the detection of MHWs. We show that MHWs detected in time series as short as 10 years did not have durations or intensities appreciably different from events detected in a standard 30 year long time series. We also show that the output of our MHW algorithm for time series missing less than 25% data did not differ appreciably from a complete time series, and that the level of allowable missing data could cautiously be increased to 50% when gaps were filled by linear interpolation. Finally, linear long-term trends of 0.10°C/decade or greater added to a time series caused larger changes (increases) to the count and duration of detected MHWs than shortening a time series to 10 years or missing more than 25% of the data. The long-term trend in a time series has the largest effect on the detection of MHWs and has the largest range in added uncertainty in the results. Time series length has less of an effect on MHW detection than missing data, but adds a larger range of uncertainty to the results. We provide suggestions for best practices to improve the accuracy of MHW detection with sub-optimal time series and show how the accuracy of these corrections may change regionally.

**Links:** [PDF](https://www.frontiersin.org/articles/10.3389/fmars.2019.00737/full) &middot; [Code](https://github.com/robwschlegel/MHWdetection) &middot; [Project](https://robwschlegel.github.io/MHWdetection/) &middot; [Poster](https://robwschlegel.github.io/MHWdetection/portrait.pdf)
