---
title: 'Drivers of change in Arctic fjord socio-ecological systems: Examples from
  the European Arctic'
date: '2023-01-05'
author:
  - RW Schlegel
  - I Bartsch
  - K Bischof
  - LR Bjørst
  - H Dannevig
  - N Diehl
  - P Duarte
  - GK Hovelsrud
  - T Juul-Pedersen
  - A Lebrun
  - L Merillet
  - C Miller
  - C Ren
  - M Sejr
  - JE Søreide
  - TR Vonnahme
  - J-P Gattuso
subtitle: '*Cambridge Prisms: Coastal Futures*'
type: Journal article
categories:
  - R
  - Arctic
  - fjord
  - social
---

Fjord systems are transition zones between land and sea, resulting in complex and dynamic environments. They are of particular interest in the Arctic as they harbour ecosystems inhabited by a rich range of species and provide many societal benefits. The key drivers of change in the European Arctic (i.e., Greenland, Svalbard, and Northern Norway) fjord socio-ecological systems are reviewed here, structured into five categories: cryosphere (sea ice, glacier mass balance, and glacial and riverine discharge), physics (seawater temperature, salinity, and light), chemistry (carbonate system, nutrients), biology (primary production, biomass, and species richness), and social (governance, tourism, and fisheries). The data available for the past and present state of these drivers, as well as future model projections, are analysed in a companion paper. Changes to the two drivers at the base of most interactions within fjords, seawater temperature and glacier mass balance, will have the most significant and profound consequences on the future of European Arctic fjords. This is because even though governance may be effective at mitigating/adapting to local disruptions caused by the changing climate, there is possibly nothing that can be done to halt the melting of glaciers, the warming of fjord waters, and all of the downstream consequences that these two changes will have. This review provides the first transdisciplinary synthesis of the interactions between the drivers of change within Arctic fjord socio-ecological systems. Knowledge of what these drivers of change are, and how they interact with one another, should provide more expedient focus for future research on the needs of adapting to the changing Arctic.

**Links:** [PDF](https://www.cambridge.org/core/journals/cambridge-prisms-coastal-futures/article/drivers-of-change-in-arctic-fjord-socioecological-systems-examples-from-the-european-arctic/1129E92425F6012F9610D8C9C172B2F0) &middot; [Code](https://github.com/FACE-IT-project/WP1/blob/main/code/review_paper.R) &middot; [Dataset](https://doi.pangaea.de/10.1594/PANGAEA.953115)
