---
title: A dataset for investigating socio-ecological changes in Arctic fjords
date: '2023-08-22'
author:
  - RW Schlegel
  - J-P Gattuso
subtitle: '*Earth System Science Data*'
type: Journal article
categories:
  - R
  - Arctic
  - fjord
  - social
---

The collection of in situ data is generally a costly process, with the Arctic being no exception. Indeed, there has been a perception that the Arctic is lacking in situ sampling; however, after many years of concerted effort and international collaboration, the Arctic is now rather well sampled, with many cruise expeditions every year. For example, the GLODAP (Global Ocean Data Analysis Project) product has a greater density of in situ sampling points within the Arctic than along the Equator. While this is useful for open-ocean processes, the fjords of the Arctic, which serve as crucially important intersections of terrestrial, coastal, and marine processes, are sampled in a much more ad hoc process. This is not to say they are not well sampled but rather that the data are more difficult to source and combine for further analysis. It was therefore noted that the fjords of the Arctic are lacking in FAIR (findable, accessible, interoperable, and reusable) data. To address this issue, a single dataset has been created from publicly available, predominantly in situ data from seven study sites in Svalbard and Greenland. After finding and accessing the data from a number of online platforms, they were amalgamated into a single project-wide standard, ensuring their interoperability. The dataset was then uploaded to PANGAEA so that it can be findable and reusable in the future. The focus of the data collection was driven by the key drivers of change in Arctic fjords identified in a companion review paper. To demonstrate the usability of this dataset, an analysis of the relationship between the different drivers was performed. Via the use of an Arctic biogeochemical model, these relationships were projected forward to 2100 via Representative Carbon Pathways (RCPs) 2.6, 4.5, and 8.5. This dataset is a work in progress, and as new datasets containing the relevant key drivers are released, they will be added to an updated version planned for the middle of 2024. The dataset (Schlegel and Gattuso, 2022) is available on PANGAEA at https://doi.org/10.1594/PANGAEA.953115. A live version is available at the FACE-IT WP1 site and can be accessed by clicking the “Data access” tab: https://face-it-project.github.io/WP1/ (last access: 17 August 2023)

**Links:** [PDF](https://essd.copernicus.org/articles/15/3733/2023/essd-15-3733-2023.pdf) &middot; [Code](https://github.com/FACE-IT-project/WP1/blob/main/code/data_paper.R) &middot; [Dataset](https://doi.pangaea.de/10.1594/PANGAEA.953115)
