---
title: Marine cold-spells
date: '2021-01-03'
author:
  - RW Schlegel
  - S Darmaraki
  - JA Benthuysen
  - K Filbee-Dexter
  - ECJ Oliver
subtitle: In *Progress in Oceanography*.
type: Journal article
categories:
  - R
  - marine cold-spells
---

Characterising ocean temperature variability and extremes is fundamental for understanding the thermal bounds in which marine ecosystems have adapted. While there is growing evidence of how marine heatwaves threaten marine ecosystems, prolonged periods of extremely cold ocean temperatures, marine cold-spells, have received less global attention. We synthesize the literature on cold ocean temperature extremes and their ecological impacts and physical mechanisms. Ecological impacts of these events were observed across a range of species and biophysical processes, including mass mortalities, range shifts, marine habitat loss, and altered phenology. The development of marine cold-spells is often due to wind-induced ocean processes, but a range of physical mechanisms are documented in the literature. Given the need for consistent comparison of marine cold-spells, we develop a definition for detecting these events from temperature time series and for classifying them into four categories. This definition is used to consistently detect marine cold-spells globally over the satellite record and to compare the characteristics of notable cold events. Globally, marine cold-spells’ occurrence, duration, and intensity are decreasing, with some areas, such as the Southern Ocean, showing signs of increase over the past 15 years. All marine cold-spell categories are affected by these decreases, with the exception of “IV Extreme” events, which were so rare that there has been little decrease. While decreasing occurrences of marine cold-spells could be viewed as providing a beneficial reduction in cold stress for marine ecosystems, fewer cold spells will alter the temperature regime that marine ecosystems experience and could have important consequences on ecological structure and function.

**Links:** [PDF](https://www.sciencedirect.com/science/article/am/pii/S0079661121001683) &middot; [Code](https://github.com/robwschlegel/MCSglobal) &middot; [Source](https://www.sciencedirect.com/science/article/abs/pii/S0079661121001683)
