---
title: Predominant Atmospheric and Oceanic Patterns during Coastal Marine Heatwaves
date: '2017-10-17'
author:
  - RW Schlegel
  - ECJ Oliver
  - S Perkins-Kirkpatrick
  - A Kruger
  - AJ Smit
subtitle: In *Frontiers in Marine Science*.
type: Journal article
categories:
  - R
  - coastal
  - atmosphere
  - ocean
---

As the mean temperatures of the worlds oceans increase, it is predicted that marine heatwaves (MHWs) will occur more frequently and with increased severity. However, it has been shown that variables other than increases in sea water temperature have been responsible for MHWs. To better understand these mechanisms driving MHWs we have utilized atmospheric (ERA-Interim) and oceanic (OISST, AVISO) data to examine the patterns around southern Africa during coastal (<400 m from the low water mark; measured in situ) MHWs. Nonmetric multidimensional scaling (NMDS) was first used to determine that the atmospheric and oceanic states during MHW are different from daily climatological states. Self-organizing maps (SOMs) were then used to cluster the MHW states into one of nine nodes to determine the predominant atmospheric and oceanic patterns present during these events. It was found that warm water forced onto the coast via anomalous ocean circulation was the predominant oceanic pattern during MHWs. Warm atmospheric temperatures over the subcontinent during onshore or alongshore winds were the most prominent atmospheric patterns. Roughly one third of the MHWs were clustered into a node with no clear patterns, which implied that they were not forced by a recurring atmospheric or oceanic state that could be described by the SOM analysis. Because warm atmospheric and/or oceanic temperature anomalies were not the only pattern associated with MHWs, the current trend of a warming earth does not necessarily mean that MHWs will increase apace; however, aseasonal variability in wind and current patterns was shown to be central to the formation of coastal MHWs, meaning that where climate systems shift from historic records, increases in MHWs will likely occur.

**Links:** [PDF](https://www.frontiersin.org/articles/10.3389/fmars.2017.00323/full) &middot; [Code](https://github.com/robwschlegel/AHW)
