---
title: 'Climate Change in Coastal Waters: Time Series Properties Affecting Trend Estimation'
date: '2016-12-15'
author:
  - RW Schlegel
  - AJ Smit
subtitle: In *Journal of Climate*.
type: Journal article
categories:
  - time series analysis
  - R
---

In South Africa, 129 in situ temperature time series of up to 43 years are used for investigations of the thermal characteristics of coastal seawater. They are collected with handheld thermometers or underwater temperature recorders (UTRs) and are recorded at precisions from 0.5° to 0.001°C. Using the natural range of seasonal signals and variability for 84 of these time series, their length, decadal trend, and data precision were systematically varied before fitting generalized least squares (GLS) models to study the effect these variables have on trend detection. The variables that contributed most to accurate trend detection, in decreasing order, were time series length, decadal trend, variance, percentage of missing data (% NA), and measurement precision. Time series greater than 30 years in length are preferred and although larger decadal trends are modeled more accurately, modeled significance (p value) is largely affected by the variance present. The risk of committing both type-1 and type-2 errors increases when ≥5% NA is present. There is no appreciable effect on model accuracy between measurement precision of 0.1°–0.001°C. Measurement precisions of 0.5°C require longer time series to give equally accurate model results. The implication is that the thermometer time series in this dataset, and others around the world, must be at least two years longer than their UTR counterparts to be useful for decadal-scale climate change studies. Furthermore, adding older lower-precision UTR data to newer higher-precision UTR data within the same time series will increase their usefulness for this purpose.

**Links:** [PDF](https://journals.ametsoc.org/doi/10.1175/JCLI-D-16-0014.1) &middot; [Code](https://github.com/robwschlegel/Trend_Analysis)
