---
title: Underwater light environment in Arctic fjords
date: '2024-06-14'
author:
  - RW Schlegel
  - RK Singh
  - B Gentili
  - S Bélanger
  - LC de la Guardia
  - D Krause-Jensen
  - CA Miller
  - M Sejr
  - J-P Gattuso
subtitle: '*Earth System Science Data*'
type: Journal article
categories:
  - R
  - Arctic
  - fjord
  - light
  - dataset
---

Most inhabitants of the Arctic live near the coastline, which includes fjord systems where socio-ecological coupling with coastal communities is dominant. It is therefore critically important that the key aspects of Arctic fjords be measured as well as possible. Much work has been done to monitor temperature and salinity, but in-depth knowledge of the light environment throughout Arctic fjords is lacking. This is particularly problematic knowing the importance of light for benthic ecosystem engineers such as macroalgae, which also play a major role in ecosystem function. Here we document the creation and implementation of a high-resolution (∼50–150 m) gridded dataset for surface photosynthetically available radiation (PAR), diffuse attenuation of PAR through the water column (KPAR), and PAR available at the seafloor (bottom PAR) for seven Arctic fjords distributed throughout Svalbard, Greenland, and Norway during the period 2003–2022. In addition to KPAR and bottom PAR being available at a monthly resolution over this time period, all variables are available as a global average, annual averages, and monthly climatologies, with standard deviations provided for the latter two. Throughout most Arctic fjords, the interannual variability of monthly bottom PAR is too large to determine any long-term trends. However, in some fjords, bottom PAR increases in spring and autumn and decreases in summer. While a full investigation into these causes is beyond the scope of the description of the dataset presented here, it is hypothesized that this shift is due to a decrease in seasonal ice cover (i.e. enhanced surface PAR) in the shoulder seasons and an increase in coastal runoff (i.e. increased turbidity and decreased surface PAR) in summer. A demonstration of the usability of the dataset is given by showing how it can be combined with known PAR requirements of macroalgae to track the change in the potential distribution area for macroalgal habitats within fjords with time. The datasets are available on PANGAEA at https://doi.org/10.1594/PANGAEA.962895 (Gentili et al., 2023a) and https://doi.org/10.1594/PANGAEA.965460 (Gentili et al., 2024). A toolbox for downloading and working with this dataset is available in the form of the FjordLight R package, which is available via CRAN (Gentili et al., 2023b, https://doi.org/10.5281/zenodo.10259129) or may be installed via GitHub: https://face-it-project.github.io/FjordLight (last access: 29 April 2024).

**Links:** [PDF](https://essd.copernicus.org/articles/16/2773/2024/) &middot; [Code](https://github.com/FACE-IT-project/fjord_PAR) &middot; [Dataset](https://doi.pangaea.de/10.1594/PANGAEA.962895) &middot; [Project](https://face-it-project.github.io/FjordLight/)
