---
title: A novel approach to quantify metrics of upwelling intensity, frequency, and
  duration
date: '2021-07-08'
author:
  - A Abrahams
  - RW Schlegel
  - AJ Smit
subtitle: '*PLOS One*.'
type: Journal article
categories:
  - R
  - coastal
  - atmosphere
  - ocean
---

The importance of coastal upwelling systems is widely recognized. However, several aspects of the current and future behaviors of these systems remain uncertain. Fluctuations in temperature because of anthropogenic climate change are hypothesized to affect upwelling-favorable winds and coastal upwelling is expected to intensify across all Eastern Boundary Upwelling Systems. To better understand how upwelling may change in the future, it is necessary to develop a more rigorous method of quantifying this phenomenon. In this paper, we use SST data and wind data in a novel method of detecting upwelling signals and quantifying metrics of upwelling intensity, duration, and frequency at four sites within the Benguela Upwelling System. We found that indicators of upwelling are uniformly detected across five SST products for each of the four sites and that the duration of those signals is longer in SST products with higher spatial resolutions. Moreover, the high-resolution SST products are significantly more likely to display upwelling signals at 25 km away from the coast when signals were also detected at the coast. Our findings promote the viability of using SST and wind time series data to detect upwelling signals within coastal upwelling systems. We highlight the importance of high-resolution data products to improve the reliability of such estimates. This study represents an important step towards the development of an objective method for describing the behavior of coastal upwelling systems.

**Links:** [PDF](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0254026) &middot; [Code](https://github.com/AmierohAbrahams/Upwelling_MCS)
