---
title: What and where? Predicting invasion hotspots in the Arctic marine realm
date: '2020-05-14'
author:
  - J Goldsmit
  - CW McKindsey
  - RW Schlegel
  - DB Stewart
  - P Archambault
  - KL Howland
subtitle: In *Global change biology*.
type: Journal article
categories:
  - R
  - SDM
---

The risk of aquatic invasions in the Arctic is expected to increase with climate warming, greater shipping activity and resource exploitation in the region. Planktonic and benthic marine aquatic invasive species (AIS) with the greatest potential for invasion and impact in the Canadian Arctic were identified and the 23 riskiest species were modelled to predict their potential spatial distributions at pan-Arctic and global scales. Modelling was conducted under present environmental conditions and two intermediate future (2050 and 2100) global warming scenarios. Invasion hotspots—regions of the Arctic where habitat is predicted to be suitable for a high number of potential AIS—were located in Hudson Bay, Northern Grand Banks/Labrador, Chukchi/Eastern Bering seas and Barents/White seas, suggesting that these regions could be more vulnerable to invasions. Globally, both benthic and planktonic organisms showed a future poleward shift in suitable habitat. At a pan-Arctic scale, all organisms showed suitable habitat gains under future conditions. However, at the global scale, habitat loss was predicted in more tropical regions for some taxa, particularly most planktonic species. Results from the present study can help prioritize management efforts in the face of climate change in the Arctic marine ecosystem. Moreover, this particular approach provides information to identify present and future high-risk areas for AIS in response to global warming.

**Links:** [Code](https://github.com/robwschlegel/ArcticInvasion) &middot; [Source](https://onlinelibrary.wiley.com/doi/full/10.1111/gcb.15159)
